services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: overleaf-server-docs
    stdin_open: true
    tty: true
    hostname: overleaf-server-docs
    command: serve --dev-addr=0.0.0.0:8000
    ports: 
      - 8000:8000
    restart: unless-stopped
    volumes:
      - .:/docs:ro