site_name: Overleaf Server Docs
repo_url: https://github.com/overleaf
theme:
  language: en
  name: material
  favicon: assets/favicon.ico
  logo: assets/overleaf-o-white.svg
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.share
    - navigation.tabs
    - navigation.footer
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate
plugins:
  - search
  - markdownextradata
extra:
  generator: true
  versions:
    community-edition-full: Overleaf Community Edition
    community-edition-short: Community Edition
    server-pro-full: Overleaf Server Pro
    server-pro-short: Server Pro
    copyright: Overleaf part of Digital Science
    latest-two-point-releases-of-current-version: 4.1.0 and 4.1.1
    last-released-point-release-of-previous-major-version: 3.5.11
markdown_extensions:
  - md_in_html
  - admonition
  - toc:
      permalink: true
nav:
  - Home: 
    - Welcome: index.md
  - Getting started:
    - Planning for success: getting-started/index.md
    - What skills do I need?: getting-started/what-skills-do-i-need.md
    - Hardware requirements: getting-started/hardware-requirements.md
    - Software requirements: getting-started/software-requirements.md
  - Installation: installation.md
  - Configuration:
    - setup/index.md
    - LDAP: setup/changing-the-colors.md
    - SSO:
      - setup/extensions/index.md
      - Azure: setup/extensions/python-markdown.md
      - Okta: setup/extensions/python-markdown.md
  - Administration: administration.md
  - Release notes: release-notes.md
  - How to upgrade: upgrade.md
  - Troubleshooting: troubleshooting.md
  