site_name: Overleaf Server Docs
repo_url: https://github.com/mlevans0/overleaf-server-docs
edit_uri: edit/main/docs/
theme:
  language: en
  name: material
  favicon: assets/favicon.ico
  logo: assets/overleaf-logo-white.svg
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    tag:
      server_pro: fontawesome/solid/tag
  features:
    - search.share
    - navigation.tabs
    - navigation.footer
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.edit
    - navigation.expand
plugins:
  - search
  - markdownextradata
  - tags:
      enabled: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
extra:
  generator: true
  verbatim_strings:
    .Image: "{{.Image}}"
  versions:
    community-edition-full: Overleaf Community Edition
    community-edition-short: Server CE
    server-pro-full: Overleaf Server Pro
    server-pro-short: Server Pro
    toolkit-full: Overleaf Toolkit
    toolkit-short: Toolkit
    copyright: Overleaf part of Digital Science
    latest-two-point-releases-of-current-version: 5.0.3
    last-released-point-release-of-previous-major-version: 3.5.15, 4.2.3 and 4.2.4
  tags:
    Server Pro: server_pro
extra_css:
  - assets/extra.css
markdown_extensions:
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: 
    - Welcome: index.md
  - Getting started:
    - Planning for success: getting-started/index.md
    - What skills do I need?: getting-started/what-skills-do-i-need.md
    - Hardware requirements: getting-started/hardware-requirements.md
    - Software requirements: getting-started/software-requirements.md
    - Overleaf microservices: getting-started/microservices.md
  - Installation: 
    - Using the Overleaf Toolkit: installation/using-the-toolkit.md
    # - Using Docker Compose: installation/using-docker-compose.md
    - Post-installation tasks: installation/post-installation-tasks.md
  - Configuration: 
    - Overleaf Toolkit: 
      - configuration/overleaf-toolkit.md
      - Toolkit settings: configuration/toolkit-settings.md
    - Branding: configuration/branding.md
    - TLS Proxy: configuration/tls-proxy.md
    - Configuring email: configuration/email.md
    - Configuring S3: configuration/s3.md
    - Server Pro: 
      - Getting Server Pro: configuration/getting-server-pro.md
      - LDAP/AD: configuration/ldap.md
      - SAML 2.0: configuration/saml2.md
      - Templates system: configuration/templates-system.md
      - Git integration: configuration/git-bridge.md
    - Environment variables: configuration/environment-variables.md
    - Localization: configuration/localization.md
    - Logging: configuration/logging.md
#  - Administration: 
#    - administration.md
#    - Using the Overleaf Toolkit: administration/using-the-toolkit.md
  - Maintenance: 
    - Data and Backups: maintenance/data-and-backups.md
    - Horizontal scaling: maintenance/horizontal-scaling.md
  - Guides :
      - For users: guides/for-users.md
      - For administrators: 
        - User management: guides/user-management.md
        - Project management: guides/project-management.md
        - Email migration: guides/email-migration.md
        - Full project history migration: guides/full-project-history-migration.md
        - Docker Compose to Toolkit migration: guides/docker-compose-to-toolkit-migration.md
        - S3 migration: guides/s3-migration.md
        - Troubleshooting: 
          - Gathering information : guides/troubleshooting.md
          - Common problems: guides/common-problems.md
  - Release notes:
    - 5.x.x: release-notes/Release-Notes-5.x.x.md
    - 4.x.x: release-notes/Release-Notes--4.x.x.md
    - 3.x.x: release-notes/Release-Notes-3.x.x.md
    - 2.x.x: release-notes/Release-Notes-2.0.md
    - 1.0.0: release-notes/Release-Notes---1.0.0.md
    - 0.6.0: release-notes/Release-Notes---0.6.0.md
    - 0.5.0: release-notes/Release-Notes---0.5.0.md
    - 0.4.0: release-notes/Release-Notes---0.4.0.md
    - 0.3.0: release-notes/Release-Notes---0.3.0.md
    - 0.2.0: release-notes/Release-Notes---0.2.0.md
    - 0.1.3 and 0.1.4: release-notes/Release-Notes---0.1.3-and-0.1.4.md
    - 0.1.2: release-notes/Release-Notes---0.1.2.md